[package]
name = "the-average-benchmark"
version = "0.1.0"
edition = "2021"
publish = true

[dependencies]
num_cpus = "1.13.0"
sysinfo = "0.33.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
chrono = "0.4.40"
