apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-benchmark-api
  namespace: average-benchmark
  labels:
    app: cpu-benchmark-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-benchmark-api
  template:
    metadata:
      labels:
        app: cpu-benchmark-api
    spec:
      containers:
      - name: cpu-benchmark-api
        image: theaverageunknown/cpu-benchmark-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: discord-webhook-secret
              key: DISCORD_WEBHOOK_URL