apiVersion: v1
kind: Service
metadata:
  name: benchmark-api
  namespace: average-benchmark
  labels:
    app: benchmark-api
spec:
  type: NodePort
  selector:
    app: benchmark-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080